title: Raquel Merced # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Professional with experience in math, research, and data analysis. Trained in statistics and computer programming languages 
  with solid communication skills. Enthusiastic about organizational success and development. A team player and able to analyze, solve problems, 
  innovate, and follow through on projects.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/raquel-merced/">LinkedIn Profile</a> 
   <br>
  <a href="https://public.tableau.com/app/profile/raquel.merced">Tableau Public Portfolio</a>  
  <br>
  <br>
   <br>
  <br>
  [![Linkedin Badge](https://img.shields.io/badge/-anirudhemmadi-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/anirudhemmadi/)](https://www.linkedin.com/in/anirudhemmadi/)
   <br>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
