title: Raquel M.# your name (or website title) here
logo: "/images/profile_pic.jpg"  #"/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  As a data scientist, I specialize in developing data-driven solutions that enhance productivity, accuracy, and efficiency in internal data processing. 
  I create robust data models and logic to synthesize and analyze complex datasets, delivering actionable insights that address critical business challenges. 
  My passion lies in transforming data into strategic solutions that drive decision-making and foster innovation in dynamic environments.

  <br>
 
 <!-- <a href="https://www.linkedin.com/in/raquel-merced/">LinkedIn Profile</a> -->

  <br>
 <!-- <a href="https://public.tableau.com/app/profile/raquel.merced">Tableau Public Portfolio</a>  -->
  <br>


theme: jekyll-theme-minimal
google_analytics: G-1C99GLYG1J  # your Google Analytics tracking ID here #UA-000000-0
