title: Raquel Merced # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Professional with experience in math, research, and data analysis. Trained in statistics and computer programming languages 
  with solid communication skills. Enthusiastic about organizational success and development. A team player and able to analyze, solve problems, 
  innovate, and follow through on projects.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/raquel-merced/">LinkedIn Profile</a> 
   <br>
  <a href="https://public.tableau.com/app/profile/raquel.merced">Tableau Public Portfolio</a>  
  <br>
  <br>
   <br>
  <br>
   <br>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


site: Raquel Merced

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 3
paginate_path: "/blog/page:num/"

