title: Raquel Merced # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Professional with experience in math, research and data analysis, who enjoys applying these skills and utilizing prior experience. Trained in statistics and computer programming languages with solid communication skills.  
  <br><br>
  [Resume](/resume_page) 
  <br><br>
  <a href="https://www.linkedin.com/in/raquel-merced/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

